### ISSUE TITLE
Use Argo CD ApplicationSet to manage deployments across CDPipeline

### ISSUE THREAD

**Issue by zmotso** [epam/edp-cd-pipeline-operator#20]
cd-pipeline-operator should start managing (Create/Delete) Argo ApplicationSet object for each kind CDPipeline object.

1. When the user deletes CDPipeline, then ApplicationSet should also be removed.
2. When the user removes/adds Stage/Application from CDPipeline ApplicationSet should be updated in the part of the generator list (see Argo CD Application spec)
3. When the User creates CDPipeline, the proper ApplicationSet should be created (see format below)

 The below code represents ApplicationSet for CDPipeline `demo` with:
Stages: `dev` and `qa`
Codebases: `demo`, `myapp`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:   
  name: demo
  namespace: edp-delivery-sk-dev
spec:   
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:     
    - list:         
      - elements:        
        - stage: dev
          codebase: demo
          imageTag: main-20240108-161641
          imageRepository: registry.eks-sandbox.aws.main.edp.projects.epam.com/edp-delivery-sk-dev/demo
          cluster: in-cluster
          namespace: edp-delivery-sk-dev-demo-dev
          gitUrlPath: epmd-edp/sk-dev/demo
          versionType: default
        - stage: dev
          codebase: myapp
          imageTag: 0.1.0-SNAPSHOT.2
          imageRepository: registry.eks-sandbox.aws.main.edp.projects.epam.com/edp-delivery-sk-dev/myapp
          cluster: in-cluster
          namespace: edp-delivery-sk-dev-demo-dev
          gitUrlPath: epmd-edp/sk-dev/myapp
          versionType: edp

        - stage: qa
          codebase: demo
          imageTag: main-20240103-141431
          imageRepository: registry.eks-sandbox.aws.main.edp.projects.epam.com/edp-delivery-sk-dev/demo
          cluster: in-cluster
          namespace: edp-delivery-sk-dev-demo-qa
          gitUrlPath: epmd-edp/sk-dev/demo
          versionType: default
        - stage: qa
          codebase: myapp
          imageTag: 0.1.0-SNAPSHOT.1
          imageRepository: registry.eks-sandbox.aws.main.edp.projects.epam.com/edp-delivery-sk-dev/myapp
          cluster: in-cluster
          namespace: edp-delivery-sk-dev-demo-qa
          gitUrlPath: epmd-edp/sk-dev/myapp
          versionType: edp

  template:     
    metadata:       
      finalizers:         
        - resources-finalizer.argocd.argoproj.io
      labels:         
        app.edp.epam.com/app-name: '{{ .codebase }}'
        app.edp.epam.com/pipeline: demo
        app.edp.epam.com/stage: '{{ .stage }}'
      name: 'demo-{{ .stage }}-{{ .codebase }}'
    spec:       
      destination:         
        name: '{{ .cluster }}'
        namespace: '{{ .namespace }}'
      project: edp-delivery-sk-dev
      source:         
        helm:           
          parameters:             
            - name: image.tag
               value: '{{ .imageTag }}'
            - name: image.repository
               value: '{{ .imageRepository }}'
          releaseName: '{{ .codebase }}'
        path: deploy-templates
        repoURL: ssh://git@git.epam.com:22/{{ .gitUrlPath }}
        targetRevision: '{{ if eq .versionType "edp" }}build/{{ .imageTag }}{{ else }}{{ .imageTag }}{{ end }}'
```

From where to grab values:
```
        - stage: dev                               # get from kind: Stage
          codebase: demo                           # get from kind: CDPipeline
          imageTag: main-20240108-161641           # NaN in the beginning
          imageRepository: registry.eks-sandbox.aws.main.edp.projects.epam.com/edp-delivery-sk-dev/demo # get from kind: Codebaseimagestream
          cluster: in-cluster                      # get from kind: Stage
          namespace: edp-delivery-sk-dev-demo-dev  # get from kind: Stage
          gitUrlPath: epmd-edp/sk-dev/demo         # get from kind: codebase
          versionType: default                     # get from kind: codebase
```
