### ISSUE TITLE
Argo CD ApplicationSet should support customValues flag

### ISSUE THREAD

**Issue by zmotso** [epam/edp-cd-pipeline-operator#25]
Acceptance criteria:
- CDPipeline operator should support `customValues` flag
- This flag is always set to false when creating CR ApplicationSet

Technical details:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata: 
  name: demo-pipeline
  namespace: edp-delivery-sk-dev
spec: 
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators: 
    - list: 
        elements: 
          - cluster: in-cluster
            codebase: demo
            gitUrlPath: epmd-edp/sk-dev/demo
            imageRepository: >-
              registry.eks-sandbox.aws.main.edp.projects.epam.com/edp-delivery-sk-dev/demo
            imageTag: NaN
            namespace: edp-delivery-sk-dev-mypipe-dev
            stage: dev
            versionType: edp
            customValues: false
          - cluster: in-cluster
            codebase: myapp
            gitUrlPath: epmd-edp/sk-dev/myapp
            imageRepository: >-
              registry.eks-sandbox.aws.main.edp.projects.epam.com/edp-delivery-sk-dev/myapp
            imageTag: NaN
            namespace: edp-delivery-sk-dev-mypipe-dev
            stage: dev
            versionType: edp
            customValues: false

  templatePatch: |
    {{- if .customValues }}
    spec: 
      sources: 
        - ref: values
          repoURL: ssh://git@git.epam.com:22/epmd-edp/sk-dev/edp-gitops
          targetRevision: main
        - helm: 
            parameters: 
              - name: image.tag
                value: '{{ .imageTag }}'
              - name: image.repository
                value: registry.eks-sandbox.aws.main.edp.projects.epam.com/edp-delivery-sk-dev/{{ .codebase }}
            releaseName: '{{ .codebase }}'
            valueFiles: 
              - $values/demo/{{ .stage }}/{{ .codebase }}-values.yaml
          path: deploy-templates
          repoURL: ssh://git@git.epam.com:22/{{ .gitUrlPath }}
          targetRevision: '{{ if eq .versionType "edp" }}build/{{ .imageTag }}{{ else }}{{ .imageTag }}{{ end }}'
    {{- end }}

  template: 
    metadata: 
      finalizers: 
        - resources-finalizer.argocd.argoproj.io
      labels: 
        app.edp.epam.com/app-name: '{{ .codebase }}'
        app.edp.epam.com/pipeline: demo
        app.edp.epam.com/stage: '{{ .stage }}'
      name: 'demo-{{ .stage }}-{{ .codebase }}'
    spec: 
      destination: 
        name: '{{ .cluster }}'
        namespace: '{{ .namespace }}'
      project: edp-delivery-sk-dev

      source: 
        helm: 
          parameters: 
            - name: image.tag
              value: '{{ .imageTag }}'
            - name: image.repository
              value: registry.eks-sandbox.aws.main.edp.projects.epam.com/edp-delivery-sk-dev/{{ .codebase }}
          releaseName: '{{ .codebase }}'
        path: deploy-templates
        repoURL: ssh://git@git.epam.com:22/{{ .gitUrlPath }}
        targetRevision: '{{ if eq .versionType "edp" }}build/{{ .imageTag }}{{ else }}{{ .imageTag }}{{ end }}'
```
