### ISSUE TITLE
Implement capsule capabilities to the cd-pipeline operator

### ISSUE THREAD

**Issue by zmotso** [epam/edp-cd-pipeline-operator#4]
The cd-pipeline operator can use a capsule for multi-tenancy.
We can use the cd-pipeline operator ServiceAccount as tenant owner.

See [https://capsule.clastix.io/docs/general/tutorial/#assign-tenant-ownership] "Robot account as tenant owner".
Example:
```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata: 
  name: delivery-dev
spec:   
  owners:     
    - kind: ServiceAccount
      name: system:serviceaccount:delivery-dev:cd-pipeline-operator
```
```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: CapsuleConfiguration
metadata:  
  name: default
spec:  
  userGroups:
    - capsule.clastix.io
    - system:serviceaccounts:delivery-dev
```
